apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: cert-manager
  labels:
    belacca.com/component: cert-manager
    belacca.com/stage: native-staging
spec:
  interval: 1h
  url: https://charts.jetstack.io
