apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dex
  namespace: dex
  labels:
    belacca.com/project: platform
    belacca.com/component: identity
spec:
  interval: 1h
  url: https://charts.dexidp.io
