apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - config.yaml
  - pvc.yaml
  - deployment.yaml
  - network-policy.yaml

configMapGenerator:
  - name: native-observability-contracts
    namespace: observability
    files:
      - synthetic-contracts.json
    options:
      disableNameSuffixHash: true
      labels:
        belacca.com/stage: native-production
        belacca.com/project: observability
