apiVersion: v1
data:
    flux-web-client-secret: ENC[AES256_GCM,data:AsUpNNlqk29WyD5zhenKBbuZPDq8NS2QzIGtkoTmqS3PtnqK37yb0qRGB8b++q/sWR84S1Qh1js48cGjrSw8oiwfuLhWw4z/12JrdrZYggNnX9zEb9hr0Q==,iv:y2BMPEtzwYpFVzQ0G3zd7unesQtD5ubc3FaV+mvrFvw=,tag:h5UCVy8qXjXpLk3XE0WyUg==,type:str]
    headlamp-client-secret: ENC[AES256_GCM,data:3AeR5TabgcZqKAVyNBtTtrPQy+OVBdp5HF9xfwEBVS9vFbbNAiMUX01BJLVAjViErvDDsl5kmqg/vyhTWD9mahmkZawbUQHsfoND6k7zcoXS4AMpKtIZPg==,iv:hJttvOnVFpnsOPeAmxg284k7O0eAlPieeMal3uST/oA=,tag:LTw61NU/e3IerDkbQTkybw==,type:str]
    stats-client-secret: ENC[AES256_GCM,data:C1zWZbNdohErM9Tu5qtZwsiwo/G9pTitGR+KZBWfDrLA3P/SkubZE3QbqPd66Wk+qyLXOKq/t6p7hWG5cNwnvtVFASeNI5U/mWN45eLV9naY73VcLGQ/vA==,iv:+oF6oh4HXICD4CgD5XAxdlqlGIqVWTf3DmOv0IAJ02A=,tag:knhFSXwEGo1gwd4rx5NG4w==,type:str]
    azure-without-azure-client-secret: ENC[AES256_GCM,data:F2PFGmjVrqtICxK2ZwCRt3kxUxWvpzFVHu018/tkZOP/9nlcMaZ1E9iTODxKANfqtWFQ6nyRROD+odqjhp6SdpsDYHYjJftvxFY195r6QxIPH7WvTNyGhw==,iv:0TEO/mEztKDktPrdxzhWVdFInS9Yi1HKSHo6vXOuyI0=,tag:2zjDVUw4CbsZbi2S8x5U7Q==,type:str]
kind: Secret
metadata:
    name: dex-client-secrets
    namespace: dex
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOGE5WThEbkkwTHNCMGxZ
            WWxmOGl4YzRMYzFIZ2dkNUgrNDRsbEZBUXpzCmVLVS9XVlluMGlFaU82NEpFWlhQ
            L1k1M1diMmV0VEF6R1BCNzFOQk9FT3MKLS0tIDdXbnZDWit0SUlxL1BOZUM2eTVC
            Zm41MWluM3BHaTJkdnk5RUtKTmRIQ00KtGVpDGXQRPOCp+xNoHcCkDfesCFc+jBh
            zDS0LGNtarBiKxAl1+Oy4RPVrGq966WHepadlwbHmdiZpeFtAH2byQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhvf35flvr4w90jx2zcx40qpnvxapp9ucct6favsvr66quuy3vnsj4wt3r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T19:56:13Z"
    mac: ENC[AES256_GCM,data:T5nesO876NulF1cyMcpD2QUJ2MCuoZyWcC60fA+YJym7C9khIfZWBXVBuk58juW59S6yfJXi5qD7INoffUZ2SeaqFDTIFGH/DL+M5E1EJxJtoWZRolcZ/Q2F4MX6+5G6tUBniMALAPBqm075f8zgP6bL87CPoG1ZOnS4Q9qt9Q0=,iv:pwXrhcMuOqOZMUINFbKFxPBvApf8vrEzTKxcpbdP9hA=,tag:1aVyDv42PQ70ihxSTn5Xxw==,type:str]
    version: 3.13.3
