apiVersion: v1
kind: Secret
metadata:
    name: mutandae-dex-client-secret
    namespace: dex
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:D6qUxE99yZ/SOGRv2WV6CihyTwQLPKc6uCHrVW6U/ARfyoSlt8TtHd+q1Vrt1O0vpFCI0x4oqrgN7zqopAKzdw==,iv:tHLCwnOXHR2t7ubVmkDbbo49qF7JLQ7TIBMoXXxST04=,tag:xco/VU4xkE7j6LaYnjNc0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVejU3VHhOUkI4dTl4UStP
            V1BlSW9hNmROMG9hWFdvK3VaRGUzWW92dmk0CmZUNVk5eDA2U2RpSlZQOURZMUxK
            T1JQaDJkSENReUpqeHorVmk0UWRHR0EKLS0tIHZtNW5EWjhNR3JxMjZSS0liVFdG
            L3AyYXpRc3VoNzlTaDFPbHpXbndSOTAKy44fvyws4RwfiNPxH/2Tnp2JQ4Ez2aH2
            jWrNp+j7hSuws9Is9NONtb/am45xzkTA213nhVeQ8OBbciNL/pk41A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhvf35flvr4w90jx2zcx40qpnvxapp9ucct6favsvr66quuy3vnsj4wt3r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T16:19:17Z"
    mac: ENC[AES256_GCM,data:T5t2yf1QUc8gjmNxPIWVcr1GQXpq+yKn9NGUSaIX84/PMeHIyVe/If3L6qv59reQLHwJDzby922+L0C85Xg2lXdACuKUY65KmOXSRheLfY2riHC1YSEFCGsKiBotbzRYkCyEhy0I/AL9mMfoyWX58gk5Zyma6YtvStVOxY5wJYA=,iv:4Tl3WpkACbR7AnD3I1mTrptVvBt0OdwH4dY9oKhynHI=,tag:PyVB63O0klS9j4XyKdRsQg==,type:str]
    version: 3.13.3
