apiVersion: ENC[AES256_GCM,data:gkU=,iv:WW8QG+G+cKFlwsxR12g6m4I84kuPyJ97Mz1Wj3E8hhA=,tag:4tFKGWyFl9FsN8QpknnFTw==,type:str]
data:
    flux-web-client-secret: ENC[AES256_GCM,data:9ZCjl8nEnD6UvXCmRHQzHD+epvDk/93sMRSXKtv1yThFzLq1f3QeAEKfBA66YetGuVzIyyVt9ibn7e5HhoJj0QE4OPdvT5N8mIHOt7itF+6YbZ27M4BIdw==,iv:Gvs+0ohle4AHX9zAySpI2iHT3j4FF8QgT3Ncy39uO6A=,tag:r4PCYw1YBGiN79UIV5YP1g==,type:str]
    headlamp-client-secret: ENC[AES256_GCM,data:0o3QFL0ANZgCxnZ14uymjiZfCtr1NVSS47uq6Y3DuvEAq+9sUxfHLSS4KNoJCRGhxtIEj+pJuyHkAdRZ4FP8hBmQaqnXAzWHaGI2jYYIv6z+NQ4XsTA+Hg==,iv:N+T4/iB+NDuRxbtLHM0F6CZ31YqjFJAUtMCKsi3Ss58=,tag:uoloWcpYZgkXbDbBqf5h3w==,type:str]
    stats-client-secret: ENC[AES256_GCM,data:WFJMVe8gY4r/X6sEj5zENUiddrCvCV4bUrL2id0uTcNDh3LnHrMglR86uZVUBm2kOsaLX6GvahM7XY3bAGVkp86tUBwnXscCfnBsETuCryC2+St2yyolng==,iv:8aNN+T6ttMBVZVpzTAo26c/QoHS0pG60j9KfpMZUEN4=,tag:eo6y6VVqaoLSm4nZyGT9Lg==,type:str]
kind: ENC[AES256_GCM,data:RtyYI8fn,iv:4P8/UdU/egj/E4qNHGdwULNRn+bOp1tfhJsCgLJlGNk=,tag:rGigpsadzMxtBBSlszHuqQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wPNpBXtzED/cFQKas5MED4q3,iv:OjwD7LbcT8fHgleXZS9RBaMivHzFKOCFdsLrzilfnQk=,tag:2N5Aui+BO7euYQ5XGEB2jQ==,type:str]
    namespace: ENC[AES256_GCM,data:giFc,iv:Kivtz6XyB8nj0a29WfjzvjjvTKAUFNuQxvZda6bja4o=,tag:PKfImTNxn02NFdksyfzQsQ==,type:str]
type: ENC[AES256_GCM,data:LHtnARwb,iv:OsoppfEfIsfpoBG3hU5scuM/Lj0J2YuN4yxbxckDDoQ=,tag:hYAED7L1VFx0cXuVICTCUg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdXk1WDcrbFNpMnd3UFFo
            TXhUbUtnVkpNQUFuNGhHOTFLQkVFVzQ2dGs0Cm5FdlJjUkpMeFo5cnJaSTI4czFX
            TzlhODNxRy9kSW1UTUUxYlFBOEZJUjQKLS0tIGs5akt6VEM1OWZiNk5JTEtwcVo2
            aWxNajlJdmxmT2ZFR2RWdzRoVGdYTWsKPCjfuABMHIIaY9Kh+qMUw3Ieh5gC29jS
            q7BdJ5ijjK6uHH6b+U8Y3dOCG+6V6xIEY6pjjx/4wKIwry8ON8zmzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhvf35flvr4w90jx2zcx40qpnvxapp9ucct6favsvr66quuy3vnsj4wt3r
    lastmodified: "2026-08-17T21:39:07Z"
    mac: ENC[AES256_GCM,data:L6SdLvL9PioSwl2+yGK1AVcYxvInrcYHG4W5vvfT9ruC+P5ViqLbf27sxvQJ62Fy2U54ONcBTJ5OIzjsnYbPv72d591xMqZN0Jcn9sxZoP36htVMR8zPFzx5476Tcek/qZQDFbvGj7sAb/JgnP2bLxtVi5Pn7fGhaPouZcmQ0Wg=,iv:5LZhzHWAL6czgnqOA9j+uB1/lBBTxJEJYcIBrRZ7zYM=,tag:EnjnZeiB3YRvHTwX1Pf8QA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
