apiVersion: v1
data:
    flux-web-client-secret: ENC[AES256_GCM,data:bwDdm7WJriTRdIfP8mD9zYPuBoyS/Di5ONCBUrDS5lpKrIaMG85bq7NRJ0oqGEieAA9eMpSceWIe/7psJBxDkfPZd/m6b9oYP8xoPDUdDug79rSDbsOtTw==,iv:oi7Wlow/kyFLIOSnJTRavozZ8KN0zs4Q7W9Qy0sIZaI=,tag:chWm02tQjpbjXnlHD7X8xg==,type:str]
    headlamp-client-secret: ENC[AES256_GCM,data:ZJT7KPevb8osDxCKtrGCkF9r4BN/o+aI6PbqfN7eqTZsihPVCkqGwetPazeru9TYJV7+dONuEntG+0E0jo+4igtskjwNtRbhieKhjJoiHraNFGqK1WZJkQ==,iv:QB6g+YqiqujiPHQJOfOUmzk1yVoGyXH3abmnjLK9UFg=,tag:0ah5JF56l4/XKgWKlZViAA==,type:str]
    stats-client-secret: ENC[AES256_GCM,data:bxn5DhWyGOjGp+G8xD1NimwFIzuftij+txLJstdTaqtD0PoVTldikKMmmFCxQQiDVCpxYwSAPvBeKLoeV0PifBSS+hZcARrEP5ZuK/Luhl6lPFHOqAoHDw==,iv:8On6GwYTtpmtEygunKFW4Rov4hjt8JTuH+PAQS5dRZE=,tag:C+lbZKptZYj80XZ1aplm8Q==,type:str]
kind: Secret
metadata:
    name: dex-client-secrets
    namespace: dex
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLa3pSa050UllUWElsclh0
            R0hONnkva2VkWVF6Tk1sdE1ITS9JM1Z3Z2lRClFMVXIrSDBrN2dXaTRUNEc2VlFE
            TGxVQ0tUQVZqNVMrdS84VnV4Rmt3UG8KLS0tIDNjd21pdEZuU1U0Nm9vZWxmd2Fu
            UEtsU3pzclZveDJzQnJZOFgreWZoU1EKw19zjGmRtLpzExva2/KHWXZSYh90ot+w
            F42Gd+U0WsEk+18KOd32x1pEY8eDRofagPDma1X99M4o5dhGRXBDTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhvf35flvr4w90jx2zcx40qpnvxapp9ucct6favsvr66quuy3vnsj4wt3r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T16:13:00Z"
    mac: ENC[AES256_GCM,data:GXj6lYMGbDpiz4yWVa2hwNY7P9NWo+wmKh38ms62HJGQOMSU/epHqb4QzQLBc7lfqo5U4Ch8F3elYR1w1Hw0B2UHLMncYYD1u11Ci/8G5kYgou4fLCYU+Oa1+r+kMzTBi4KcurcaoLGwnPGe2YJ1IsZ5XSDnoKOUL4twC1BVON4=,iv:WjrxEtMPO693p3znV22ThpFwrQ4NTseKjfqoP7HuUU0=,tag:aso+0rdRvrXBtDP7O50Brg==,type:str]
    version: 3.13.3
