apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - secrets
  - longhorn
  - policy-system
  - edge
  - cert-manager
  - tls
  - routing
  - native-sources.yaml
  - native-policy-system.yaml
  - native-applications.yaml
  - native-platform-applications.yaml
  - notifications.yaml
