apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: analytics
  namespace: flux-system
  labels:
    belacca.com/project: analytics
spec:
  interval: 10m
  path: ./clusters/vmi3474918/analytics
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
