apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pong
  namespace: flux-system
  labels:
    belacca.com/project: pong
spec:
  interval: 10m
  path: ./k8s/overlays/server
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: cloudnativepong
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: portfolio
  namespace: flux-system
  labels:
    belacca.com/project: portfolio
  annotations:
    belacca.com/release: "site-8a48bd551af3d0996ad0eaf85f069ef1d9eaf069"
spec:
  interval: 10m
  path: ./deploy
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: francesco-belacca-site
