apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dex
  namespace: flux-system
  labels:
    belacca.com/project: platform
    belacca.com/component: identity
spec:
  interval: 10m
  path: ./clusters/vmi3474918/dex
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
