apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - sources.yaml
  - applications.yaml
  - routing-flux.yaml
  - analytics-flux.yaml
  - notifications.yaml
  - observability-flux.yaml
  - policies
  - headlamp
  - traefik-acme-pvc.yaml
  - traefik-config.yaml
