apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: belacca-routing
  namespace: flux-system
  labels:
    belacca.com/project: platform
spec:
  interval: 10m
  path: ./clusters/vmi3474918/routing
  prune: true
  wait: true
  dependsOn:
    - name: pong
    - name: portfolio
  sourceRef:
    kind: GitRepository
    name: flux-system
