apiVersion: v1
kind: Secret
metadata:
    name: mutandae-api-tokens
    namespace: mutandae
type: Opaque
stringData:
    tokens.json: ENC[AES256_GCM,data:gTw1LNRkKD4TRq8mXnBKBun0jxguo4JJFdO5k0kqZpvb62w7a+H2wYAcn7OINLcWicpA3eRCylfihVdL02bXXPb/vzEbYoVHykJSJykRi44WK85mcHvnM0jYB+1lX4qBFqdxDGrdH/CdZBiY8saXLUPwqLtQnYZKp9co6//YMVywqKd5fOgI5UVUl0gDbCt4HA==,iv:FgEH1K411BdCwvX783dSrkIgSQ8AuJQotJNi1+KLjkE=,tag:9LOmUqoy7zk5h7Nr3jAZ3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRUNRTFphU2ZWL2ZncW00
            dGtQWXFGVzdJVDZVeXQvQnJJNnlJcFhtMmhjCi9INUsxSEwzTW92UGZJWkgwVmg0
            U2NDR3JaeUpPRDJJSmN6QVdOaVRBVlUKLS0tIHR3UElPM21VY1FGQVlJaXNrOUdn
            dHdIaTBidE5PeXB0eXhoN2pXTUYrZWMKLuR7t0kRbLNI88D6G3RE36FAaYu5qBwc
            zYb68zuVwAJ04x4wcTGimAwF4gY6RLIwCkrRNrY/DNPKmfWMwyN0Ww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhvf35flvr4w90jx2zcx40qpnvxapp9ucct6favsvr66quuy3vnsj4wt3r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T14:02:40Z"
    mac: ENC[AES256_GCM,data:CWEYtiU7Hqyt0GrWEotGTBwBpBhWbz7Kwz7S2S0DR+98Uo1ud8gs2MgZVHQ7AazTSXZNTyEKEgEd+qcBootU+6udLK5F2ynGnyF8feeaFp+oCls44zoMGNLBPQ/AqH1lnfoxChFmKspC15RJKeTRegtZbsNA2eDG5wtKP9dCFtg=,iv:uiXLPw6D4McQBn7Ppr+IWaCuNwR5aImSq+cSlLKTUjs=,tag:6a5P5qESoyGlsLdl9uz31Q==,type:str]
    version: 3.13.3
