apiVersion: v1
kind: Secret
metadata:
    name: mutandae-api-tokens
    namespace: mutandae
type: Opaque
stringData:
    tokens.json: ENC[AES256_GCM,data:Tjs=,iv:Awwkt4bAxXxWe1UYajw4yWUO6e3iGvD7cXcAWVqP1Cg=,tag:DdYIsG/gKLbX2OPY07Sv2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMTlqYmRBUW5YdUcxcldW
            MlNFaENGU2kzODQyazdEY0ZwRUZuaVovdUNvCjk5MmEzQ3ZjcnJKbFZvODh0T1hB
            UTlIOThIQjY5cVhiQlJhcm4yTTZtUzAKLS0tIEl4N1MxVHRKRTNUbTVVRlRldG1n
            L012VDdDQ1owMUhzWkNYUWlySEFGbzQKUhctdZgxalSxH2q0/5GvjG1LQ6BkK0a/
            m9u1WbFFQ2772LaaJ8TPlw98PsKgRvlweKtrJUAyU6UD7jtvEnlJYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhvf35flvr4w90jx2zcx40qpnvxapp9ucct6favsvr66quuy3vnsj4wt3r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T15:33:20Z"
    mac: ENC[AES256_GCM,data:qY/1dmqbwczqSqko5NEkGGhhn+NHT9m+MioOsyvzjR8cirOHKy0Gl93rk28JiaQr47JsrNFKWfmO9Evy8p7EzTjmPo1lGaNbJLNvunHpsIgor1gzq730dnfAViGOW+v4+i/cfUhD9JDZsHMmjtfg/UtCEFQa446D0lDtKkQg5So=,iv:LAGfbW8+5i6FNvIx7ALyhu+kd/+Gxzaifb0Wsm3ROp0=,tag:9oz7KhdceG8B7phEZ6P3Cg==,type:str]
    version: 3.13.3
