apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mutandae-live-documents
  namespace: mutandae
  labels:
    belacca.com/project: mutandae
    belacca.com/component: encrypted-documents
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mutandae-preview-documents
  namespace: mutandae
  labels:
    belacca.com/project: mutandae
    belacca.com/component: encrypted-documents
    belacca.com/stage: preview
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
