apiVersion: v1
kind: Secret
metadata:
    name: mutandae-intake-preview
    namespace: mutandae
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:WvEqB0CsL3m41U0/gWKEeKYnTthEtfgLmK1WAJOe5aBpD+RwLCd8ODmbjV+q7T0AU8woX2YZkbMAKGePbHWzmmZ+NhFjB/xcfcy/NkottieybglWw/IARruIGysh3RoGFAyBe8akNeaxRlUL/+OL3NLVf/nEsWLvXMCdbglS8yz2nTssDlLKbAZNULi4SQvcb82uM4AqLdq7MOhJkKU3+QVGDCC/Jq7k8iBt,iv:aSKpta6CJAbXWzftK//wRPwlpZcerlv1wMv/h86YmUM=,tag:bABDMQ8gLu7w5GIKCyxqUA==,type:str]
    MUTANDAE_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:pZiC0q1TtGNHRUxkMXqszM/Zg61o/MbE8JCxZ/QLtgJa/C6Wuxtxva+3uYrU5SYkZScwD/4W90LWzfgKFx62Eg==,iv:QXtrA0eL0lxO2xjglEUwskCbexqniPaNRUkFvhxypiY=,tag:MyucQ8ZWusjSNSq2z8CM1w==,type:str]
    MUTANDAE_SESSION_KEY: ENC[AES256_GCM,data:FhgmwSnQJ8Fwgc7s29ojBXPQP3EFUHWJ8wpZWI8QuxkGylKwoAwdLPhmCqHtgtBSCaj7OAMB5VC0u8C9GvWoPA==,iv:bPy2QoyJ+yMui87LzmeveHpOROjfXsUQ7cGGb6DagJ4=,tag:X3fPYvTsEMVG9tZuQ/XjSQ==,type:str]
    MUTANDAE_INTAKE_ENCRYPTION_KEY: ENC[AES256_GCM,data:d3VPlpViofWKyQlLZjTEx+K3w4c2mHh2HMXWIwBXnRMRwfrZ1v6mqtzpRmwnJikYUbjNO7KCh9fFAGW+Opbu5Q==,iv:tNNYPksx59rnssFTg8LhAQ2xzBwGGb3fOSUKKPeK+g0=,tag:wsMLj2zY5rNbhlIIzchhGw==,type:str]
    MUTANDAE_DOCUMENT_ENCRYPTION_KEY: ENC[AES256_GCM,data:5+iGdJ1rcarTcSLPhccECSbtBHibJ6K+yfpwFf8l8aiDQe7LPWIuCmrSh8f6u/xfz01skijOPxK2+QFzo9BeTg==,iv:oJAOm6LEZqa3/y+ZmnRWdxBbdhwL35q3v6rWeoFMCyc=,tag:InP3BVj/xFbXdV/JCJ9rVA==,type:str]
    MUTANDAE_DOCUMENT_SIGNING_KEY: ENC[AES256_GCM,data:Eh/k+iqByZNa01XTu6ex+lbF+IpGcBstC4bByLCT20cRscubKtmdV7dI8umiLNwhvCrkCce6RWMt/nf/3TGagw==,iv:gU+Su5k/E73hohxL78kmbdcFJugYrUaCyHnNlcJFkIc=,tag:dbTnRfrs0CgU7rEnlTj4Tg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZW9qWDhhYjV3Yk1jdFBB
            K1NqWXRaRnJtVXRsaHJaWFJUTTFaczUyRkc0CjFuRXBjWjhFSGQzbWt4NS9EdkRF
            UzNaNGw5b2J3ZC85SzVQL3pHUVJHZXcKLS0tICtEN2VCbGtWYmlXZDlYZzRKMUN0
            Nno5bFE4aHpPaEFLSGN2eGlObm5WVDQKyPV6wgCWHJSmYaan+DQdAMTZ8s62Jw0O
            GoEeJgSdh+liXryHwTY9j8IuFOJZ6xHPC59A2iicXLjfbBhATlAF0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhvf35flvr4w90jx2zcx40qpnvxapp9ucct6favsvr66quuy3vnsj4wt3r
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-25T16:19:17Z"
    mac: ENC[AES256_GCM,data:ueO+QH1fRxAmnz2FX+0WP6uHY0bAPhXI1hEgVtnVvJtCwoNO9iiDEoFLRgLg3O2fW0WXCofMGuJfPEnDKLgTrPCDi4xZa6WA0a+EUwwnzys1MOEJwFXD2feiVbU+zJ2r7DL1pexV/vDOOucYavGTVczayxHF1s+h/fH7RuWQ7ew=,iv:AIphJol7k7vD9thDQwyqinb0NlyV8dmoq5PkfnXbI+k=,tag:UXTIA2SPAUmJ2ywb+jx7rg==,type:str]
    version: 3.13.3
