apiVersion: v1
kind: Secret
metadata:
    name: mutandae-intake-live
    namespace: mutandae
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:mb6AZNYzyEW8XgdfZHIhGtZkWbVlfaSDHCrvQWGmBvq/oMv+1J73C9VA5BV/emnmV0SnsdqrOWMSSo3VDJd2xFChn8UhH0sCOxw8eP9ux9k8RqPuxrFmlMG6mDACFQbC7H0mnsJ5wu98qcv07IGWFnaA1dWifdZgd8kInbf8kYF+jZlgreBiQHq4Sxuo2NV8Z7BY/1DL6WJaz3KKjb7i5hFIapiUHbIR,iv:/nIyVHBee8LVLilwBFxbpmybohqf+0Uvqz7swxttnlM=,tag:NpEXlIrWxqGQATrobDlH9A==,type:str]
    MUTANDAE_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:deJ+E+Pemqe8rxALDAeAQQmVT1NnMErqcex2b5of8zfX2vziWjSY+g5GuohPunDQVPOdBSjxQHKtjr66V54TnA==,iv:9IqtaykAIY3mI+1iczN3dqrCgl509lHu9cjRz9hhpMs=,tag:eaRFx7x4LilxyrFNkI8Lxg==,type:str]
    MUTANDAE_SESSION_KEY: ENC[AES256_GCM,data:DyH02G/1k5LReJrZIJUbdpRKQ+hOTzMSFTh2UtpJ96+odLCC2cewSOwaKYXSo9ZlesPp520kt+aaOCWuAcEWiw==,iv:XKQbiJNaF0NjYToWr561X1z1FArc8I1b5Purfo3LHhk=,tag:KL5bKf2yXiACNFCWuI4MEg==,type:str]
    MUTANDAE_INTAKE_ENCRYPTION_KEY: ENC[AES256_GCM,data:554B/I0VhqyI99D4D9ZLNdxdSbf4HEX/PGRp/QoWxFxb8KGAfWt8MC23YFKMHNSjXDHLvp+6t8tfpQelvmcUJg==,iv:3baT9zGxeHS8B8udPzE1AmMIOq5dG1CU0zEFoFJbdWY=,tag:wjmTzaCD3w/T/lGSJcA7gA==,type:str]
    MUTANDAE_DOCUMENT_ENCRYPTION_KEY: ENC[AES256_GCM,data:DmqlHp/hsbJJBswPVRN3QAdCoG8kYCF3dIPSsbE/6SE5hrjLIg8K0sAqb8Stb//0cePjP51zni7072z52DeY6A==,iv:by5L9EW1l7glfkfyzx5m8n3E87vq2N2avK3uKkd+KRg=,tag:pY0k4i0wptS0EvoCdMr3Sg==,type:str]
    MUTANDAE_DOCUMENT_SIGNING_KEY: ENC[AES256_GCM,data:VzZWFFwlzT4VqAfS/zplFFodXqGjPa2O06rtcpdZxZWeHNpwT8X8ST/g9FcgXgvwwij8YxHKUCVsSRB37exAeA==,iv:l6X53mpt8HvFlwt+xCjG4iLDbw8y7/kHpf+P6mWsmLQ=,tag:2opWy8daowi9jvEyiqj61Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYzFBaEVmdWs2UEZEYTdO
            OVhBcGtPbkVkV1QxaStDKzEyRFRNZFZicGhrCisva25JMDR3Qzl3L05zMUc1RjJh
            ek5JYjVYMTZxRU82OWlGNlNtWjZxZ0UKLS0tIFJRUFd0UHVUVlJYVWlEc2Q0TEsz
            elRHTHp5ZmxzcjVhNDdCTVl3WTA5TVUK1LfLfSz74eYskcBDgm0/izm1118xl8cQ
            JgJqSKmXxEwinxbSh3Lg2vnmN++RBTZQjVMIAZ1NrRpT+AZcpTE30Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhvf35flvr4w90jx2zcx40qpnvxapp9ucct6favsvr66quuy3vnsj4wt3r
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-25T16:19:17Z"
    mac: ENC[AES256_GCM,data:fz3jiosQa31d1nKJwHLZeb90X9IJZ0EtHrtlsIRMLDrY8HR+nCypuGWl0emHVQj0iITZ/jtMHu+fzoStHfEwEkxK8SWAOZUVEqTnF0PrDqeXEoNiYzCVuNfjJMQh+aQICgcTIyCvYJM4l9Z+K9bXPiaWrjPwCHkA+mGxW3K5UKQ=,iv:I3iGF/Fj1BMrHOEueWfzA3BiciMsL5zVWD7rCJw+mw4=,tag:6/jGsDWM1/CZGYC3fzIomg==,type:str]
    version: 3.13.3
