apiVersion: v1
kind: Secret
metadata:
    name: mutandae-preview-database-credentials
    namespace: mutandae
type: Opaque
stringData:
    MUTANDAE_PREVIEW_OWNER_PASSWORD: ENC[AES256_GCM,data:sQRvlulwuFou8+emgLzn4NjNo96wCqSLsDRdu9T3EuIEG7i/g2aq6MEFOUs7EGu5M31KDYmUAQOycXtF9hophw==,iv:Rq9jk+U1bO9xFz2LJUtO8YI1iMo3nko8OmPhJEUdjoA=,tag:Fe+2/qg0TifkwsLKidJxGw==,type:str]
    MUTANDAE_PREVIEW_APP_PASSWORD: ENC[AES256_GCM,data:f0TcCLmxJ/5PST+A5rJ8E4KV6AKMz9nH1EhelWx91OtVyEvL5pKhCnGyTV7hWAMHkuhY+CfHubV/XzOhIoaNPg==,iv:T1YSXYvw/qDoeF6lmgDdYPx39zT/3LaABtSN5uySibE=,tag:08oyeAbrOfW1cpn76IHeig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbk1lN0ZEcDZhZElxQWVF
            ZllDcTg1UjRPTU92SVE2WjZuenJWWUdtUG5vClZXQWhoRVdRUDRyd0ZKWmhwM0M2
            R05oYlRPdnBKc0JwRnlSMmxUUjArT0UKLS0tIElGb3Rob1Z2bmY3VHUzS1pRbSs3
            b3ZyNGNHQWxDNXJjc2UveWJYV0ErM28KOpusUuNDDaXuFCgr1vq3J00AntYDa5sT
            p7sR7NO189t5AcnRow7Xh1vqPwV3K7UiNIStG2cdv6ehUvkNq4+6Uw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhvf35flvr4w90jx2zcx40qpnvxapp9ucct6favsvr66quuy3vnsj4wt3r
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-26T07:17:33Z"
    mac: ENC[AES256_GCM,data:Gkf6qpsNKHb0z4muaysINcG8kdAjks1jEoo8K13z+i0vwrnzCGq5rzAh6u4blviOO+Rysdeiw/j6x0VHG+jY5zEGiSLa0TLaidRKlIldedgBHWCjW+d9b+qMW5+XUR72Ik85F1ZyN1gfpYptfuYMDIFFBcJ/jFfdIAO848gfqPA=,iv:wGf/u9H9shpZ/WUCPLkijAjbvlPdzO9+xqbw0Wj+2Ns=,tag:CGz6ksND0zmGMqKmaVwULw==,type:str]
    version: 3.13.3
