apiVersion: v1
kind: Secret
metadata:
    name: mutandae-postgres-credentials
    namespace: mutandae
type: Opaque
stringData:
    POSTGRES_ADMIN_PASSWORD: ENC[AES256_GCM,data:WtzPaQSmtIHmAe9qC04NfFqMeimKjKvM7uxxq2qL6oUPxF7nMuhTqguet1aT55jkrYNUH96Qphf0yo54tJ57xw==,iv:gseBY/bK2HVENZkxID6f7lxFb+U6GTHe8SucU/yFxkI=,tag:R15GIZTnwx9opAnNzVeXHQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2R1lZUTZobFhlZlRDdk1i
            dXEyektBdjIvMmxqMzdNRUZRMWNSZmU1SDJZCmdXTGVVS1g1bDR4dTZJSVRHb0xK
            VkZCZFlnc1JFT0dWdDFZWFJ6Zzk1N0UKLS0tIENrZm9kYmRHUkozT0lKRG9adUdC
            c0JQd1JrTEg4aFVXYVdVM0o1MElpR2MK/EWy0zKJCcN1JjKexzbgvo73nYQB5vI7
            zJw3EVVjeo92n3iYml0BckBKfd+8q8GDipncGC04zeoEpH6r7lxDPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhvf35flvr4w90jx2zcx40qpnvxapp9ucct6favsvr66quuy3vnsj4wt3r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T07:25:08Z"
    mac: ENC[AES256_GCM,data:25PYBj0bkAYyAnRCkgWOGWaGScpkIiA6nCNzCxWEUefCSmx0nGDVvNKcOc7TL8VwXr07o1PUVBbBCtwXIDq5LuhhnXyhQAR1MNShd7YpNzYMWB3KPbs12YS+rJh4ukrs8jgNNd3sEyr5eUAWG8sh1FQ9jPySe0AT1JS3UjK5ZNo=,iv:ZPjDOrXqo+5yVa3Ej/RoWLRx7JLLjwzIlvoJwlPQzV4=,tag:nX7UHIj4eRhzX7aNUX9w7Q==,type:str]
    version: 3.13.3
