apiVersion: v1
kind: Secret
metadata:
    name: mutandae-live-database-credentials
    namespace: mutandae
type: Opaque
stringData:
    MUTANDAE_LIVE_OWNER_PASSWORD: ENC[AES256_GCM,data:Yx4fwXgd7AFI8skexbDI6NsIopm5a+e9tKl3eazUBy6L2awLc9Gb/FVMfi7zbd2rlJ85wZvSYRn562zGBUZpdA==,iv:sguiWA1VwM0XSf5lCKprFR4VYAfwJ/Ic+830eZu52Mg=,tag:IjnSZAkfJgnzLBwriztOaA==,type:str]
    MUTANDAE_LIVE_APP_PASSWORD: ENC[AES256_GCM,data:sOduSPhBDEYwTZei2VNrQ+JQQah517BAIeycBuOXcOPEEKJDasS9vIh04aDZtqLu+TsiAIGMZw17hHZsPIgEEA==,iv:UdQEMjjwkqNC+lWoiwBNxhy8BJsKb8QmcSjTZiVpt/A=,tag:VDS/QqOMpsujM+XiSVp+UA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeEtReTNQaVJycG1QNXVk
            aGxOSG0wdFg5Y0I4UVREVFkwYWVyMUhxS0NNCjhUQzVHZTJ6VHJaVDJMZjRVRkxq
            cjZvT3V5WU1PZWdWa29hOVJYZkp2dncKLS0tIGREK09aTmdMcFY3ejhRd1ZOb1lJ
            L3NEZDRLVGFselZHUENkOTFrQ0FXdEEKmussC0z2EoW7WA/DkCZPsed+omjfC7M0
            Uq+Cha2/Ze26dOrIx/aeWLnUY0a/huMXfQZjwkqDMtM9msUMASsO2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhvf35flvr4w90jx2zcx40qpnvxapp9ucct6favsvr66quuy3vnsj4wt3r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T07:17:33Z"
    mac: ENC[AES256_GCM,data:AhdPd4Nk1y5Lbs+2lpMzLmZnNKVEvHX1RhD7AF4o2Y8XTTy9yJFUqvIBx3UeX6E5IldxbWtIBslCHA8uLkwwylIdDrsfrr3U0jLvgonWh5Jx7EcL36ie065ekKdKFghYGUapr3HODdyBNnY1FRBfa632l1Wzm6s5OfANNGGeW8w=,iv:Eoo6Vx2fnJ8gGltubvqkO5ph1DrHDLU9qzgk2VCy91c=,tag:OR8e0ojXKjOtKb0+BL0Vrg==,type:str]
    version: 3.13.3
