apiVersion: v1
kind: Secret
metadata:
    name: mutandae-redis-auth
    namespace: mutandae
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:1qgJ5vFPb+Nfb1PkXiSiYN+FpuQT1vygk1xcEtjF2j1fTxEqYD8nFKtyaw==,iv:x4gK7hd9a90Akwgt4yggxpIlaWbA21l/9OxDPJzwSD0=,tag:bRf4deqSKVFIhe9SaxAItA==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:8ds8Dvvabe4bc2LpRbKPLkc1B3VAFLDIjld/Hi4x67uofLF2ABGv2GAMNKTodeJBfU/Px5AuitPvSmZ4LAAnSPykiu7Wl+oCUsDmuWMsUH0IiCg5luyu3iaMd3EhED1Q/hMsHUQ=,iv:ipeGjdJy11TLCDvN4llTyxiQ/OPuPS0tS8UYUPQadtQ=,tag:brhQEYcvcPS+rvLD7ECEgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVK3hKWDIvRXhpWU8rQ1c4
            UlV3bUVIUnVFeXhzQUhNZU1NbyttKzN4K0ZRCm5QNWRhYmdaQUtkd2UreVltVXhP
            TzYra2FBWEs0bkZtL016eVk4ekNOc0UKLS0tIGU3clZoNDBZaEhkeFFvSGRJY3lz
            NDFNdlVURkdhc0VVU2NabVh2YkFuZzAKorgstggINq9jfcV4jfXzXnHJqHTEkuwo
            KvfJCUksYdUCMqWOyU1BbjF7C92ZbOYwwUrYTUn3Ea8Qy5sUwjPIxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhvf35flvr4w90jx2zcx40qpnvxapp9ucct6favsvr66quuy3vnsj4wt3r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T09:11:42Z"
    mac: ENC[AES256_GCM,data:/57WG4lp1oGLqm9lY/I+8uTj/J0HmJmIimprj741xi7vePf+G/syeK4fJxV28mdRm9t+EN30sknvAwpuN8R4vWpprEC0ePucbAlKrsYq+CMqgqrV0oShIBvZYZfD/W0QVy6NxQjI2DHUvwVR3BlAyJmsuHIb/d70z2lQ1+u4Ry0=,iv:foi84TsEJqDtAosLWz7H1GzUWnC4eY3ttG+HIG9Jkd8=,tag:PN+oLfWUuP3Hp+S1tU/N9Q==,type:str]
    version: 3.13.3
