apiVersion: v1
kind: Secret
metadata:
    name: mutandae-sales-email
    namespace: mutandae
type: Opaque
stringData:
    MUTANDAE_RESEND_API_KEY: ENC[AES256_GCM,data:GuQ+ewRbVfIn5Z/7V8Op6DQ6jSp2YVAFDjsXqsqop5BmmY61,iv:aTdoMVbSnkqn4ZsAIasKE82V4ks0w9MJf7H6poir9KA=,tag:rfsryWsrDU+ayg3FIIscQA==,type:str]
    MUTANDAE_RESEND_WEBHOOK_SECRET: ENC[AES256_GCM,data:JhNc/xgI1JbXQw9P/Rcdm4OSqRFsxfqNg6jDv2i6JmjJsBW4Wmw=,iv:TeNo3eUgdcZ2GbW1hXCj/fboBnWHizBl7n5nemzcz3M=,tag:Lx5il56/iH3sf86ORm4pbw==,type:str]
    MUTANDAE_EMAIL_RECIPIENT_HASH_KEY: ENC[AES256_GCM,data:1mlklEeWuGRvRUoF8Bjb5WU3jtOF7JWkS/xtsdt5BV3cKEaUnnoHE6ArkSJuQSfdmtFev+qlX08DkphtUzhZSQ==,iv:umhYfT3Cp4FedzIvi1y6RoGWtDVRk0NDwhjLUGxxfJg=,tag:XUkHXQqMDyoFuS9GCeNl6Q==,type:str]
    MUTANDAE_EMAIL_REPLY_TO: ENC[AES256_GCM,data:iXW5CJIw8Cu2oKdhZu93XhIo,iv:7z2aeZTf7zx+bg8bK/YvdxwdZhlePsqxeOumBz0Z9fQ=,tag:aa3blXLItBvd65+z8vcnsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbVBMVGswSEh4UTh6Y2xV
            b2JsTDJRREhkMjhPYll0bDVtZ1BvdkJkUUZjCnAxK2luaDZ6OUpSdWJzTUtnQmh3
            RFhxVHMrWXJ5NE9MTXhFSS9XZDU4WHMKLS0tIFE1M056bzdSTC9YdDFOemovMUoy
            NzlubmtDazA3a2RKNmc1bUFJbFRHd0UKs6fI1F+HmgbywKAmV0S0gaXIMBL5vipY
            dskABDG8iGPW6M0zKWHb7t345EYIEKgX8kqzhjvgvkacYrvNV3vb2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhvf35flvr4w90jx2zcx40qpnvxapp9ucct6favsvr66quuy3vnsj4wt3r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T14:02:40Z"
    mac: ENC[AES256_GCM,data:LBC7F6YaH37WN4lPwh/1RlYSXOlN9gHSJL/AkpaGw3UaigVbktOFCed+4JLdm2OMvOjIRTLSEWRVEKUW6GlXRNjEMPmb9nxiVPC50c/kO9a/HvGoNp7gGZbp1euMRyP2gVLsCCQtOKjMQVM5g9O82lBoIYqjVLxSvg0sTdSv0yo=,iv:iYgJZq7Uvyih154ldvCq9MyhJyGysVEh6KwpZf4BAPU=,tag:sFbqtoFZtD7l+YgMc4tqLg==,type:str]
    version: 3.13.3
