apiVersion: v1
kind: Secret
metadata:
    name: mutandae-sales-providers
    namespace: mutandae
type: Opaque
stringData:
    MUTANDAE_OPENROUTER_API_KEY: ENC[AES256_GCM,data:AEe4Qq9jKy3+nOKo8NH1jy4IfQdQg/PhbYNvFqe6dVLawsS9pvW++EHGAjDIQDaIVQMl3/DpWW86W8UHvo+TSXutUtbUfkyPbw==,iv:erIe4NKdp29T45uAMnvnmzCPBXVm+X1nTTpn2Oi8Ddg=,tag:4GxdNAq8oDJynCDu9/lNuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRERZMmRWMzViMlVzYUJM
            eE45b2IwazBoWG9BWnNWS1ZhelBzVUFMalZzCmUzSnl0eXlYQVNiejJHUlhiSlp2
            RTM1U2dicjg3eFUvNktNYzh1NjVUOWMKLS0tIFA0ai92NW55TEFBcThIelpjaVkz
            N1VRYWpmSjdWbkw3cjdVVER2M01mQlUKNggVCAfsEzgSLyDwGjlvY7g+N3fGRewr
            jhP1vDnp9Np6u+hlUy21J+uj/mYKUq+WkiskYGOfsbHfIr1WbeqUmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhvf35flvr4w90jx2zcx40qpnvxapp9ucct6favsvr66quuy3vnsj4wt3r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T09:52:02Z"
    mac: ENC[AES256_GCM,data:IP/sFeyBfwAHSe0JUCYmCe6W6b3Agdx+odBaHK9+2OEW5cMuYq9OMKsbezep+ncZi077aPRLioq42by2NJNy2i5mucCaz0ReX5iUvr+hV0whEmuAk2TxXBgj/6k78X2bayqOMQ90tmaF0/vr8wmF9kOtls8XI2npp8rbs50rOEs=,iv:ZwaiRp3H1x8Z661a/v8GJGLp/pR75VptLkqcmlevkgM=,tag:l6XJj5acjq+RfwPlC9JmxQ==,type:str]
    version: 3.13.3
