apiVersion: v1
kind: Secret
metadata:
    name: mutandae-vault-unseal
    namespace: mutandae
    labels:
        app.kubernetes.io/name: mutandae-vault
        belacca.com/project: mutandae
        belacca.com/component: vault
type: Opaque
stringData:
    UNSEAL_KEY: ENC[AES256_GCM,data:8cIXPJwcNPLR+HcMFzSOSiLINCL6i7v7WGCDXBfdnGHOWzfJ1pE8SyLTyi0=,iv:lU20quSqK5vl/mN+WkqXSidBp3/BIn8v4ICDhGAX71g=,tag:tEXYOZTc2YhSUIbt4p3jMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTd1ZWdlN1dUpwayt6KzJM
            QVRXZCszYzJZY0h1VVYvSmlzS0xZMVVweWljCndKVlBRK1prcTQ3OERZLzR4MEMr
            ZWRwRjhLTlk2TFlGaTBuVnQ0MExjd0UKLS0tIExkMzZVTktCazBEbVhWbnZxN0tz
            ZWlpZWwzK25PaHJCR3VlZ1lhbStIV2MK9KlE5rx++wGfa/+k63p2oMz7TaA5SWrq
            kxMirn3tcqnLL9n3uXLxmE3UxUa7ZhQA2EMY0T2ooCpnX4/hQ6XK7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhvf35flvr4w90jx2zcx40qpnvxapp9ucct6favsvr66quuy3vnsj4wt3r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T14:50:49Z"
    mac: ENC[AES256_GCM,data:2fPuzcsYBVyWP/LKfEA/k9vYLmJUefo4nNsoGNLxSsvqzbpYlvg7OpSAFihq+8+AMK0W8AuEnSDfR2S3jA9ov4X6G5KjUaSJl+iZfHrB+eD1bw5pN9+k/uqapSUz9rR2y1HWSptdDooeCdGG7Dfc7KYlmj5H2JmIVPuolutIi3E=,iv:2U3s7ms9veSz97rb2oc8M2v/nqakZG1ziVuBnViSzy4=,tag:BxxMaDgjIcW5P6Ltgo6CbQ==,type:str]
    version: 3.13.3
