apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: azure-without-azure-tls
  namespace: azure-without-azure
  labels:
    belacca.com/component: tls
    belacca.com/project: azure-without-azure
    belacca.com/stage: native-production
spec:
  secretName: azure-without-azure-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - azure.belacca.com
