apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-cloudflare
    namespace: cert-manager
type: Opaque
data:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:7czihKA8kAne22hHvRfhh8QfmWtgpcD73q7i8ZUs9PKSqloVkLkQ9fBzqsc4HLFU2GJxU0hUH//AlxDuN/JA+U7trY+Q3SFw,iv:SYxx1aOgNPTQFG10WYcrWvKJBpXH7EOH/PpzxpKOHxQ=,tag:g1do/+hMpxXrNpZSI+Q4aA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdUUzdHVPOVU2MnVRaDJP
            ZWZKMGRRKy84emsyVUZ4MTdZdGhLR3ZPQmpRCm1VeGZHWmhlNzdPVjI3VnA1dmlH
            akYwVnNzeVFFQk4zUHJVUFZHeGNnSVkKLS0tIDZEYWc1dnBHU3dmZzFqNlRSNmFD
            VmhGMXBKOU1WVkQ3RTR6MWlZdmJZN2MKQgkD3Hq+YDz+j0+05tz8sT2NA/ix7GsN
            1+PtKyrI/ubOqHrxnzaRvwzPdBrhyHybtTNRFn3ywUKURBDiGvnulQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhvf35flvr4w90jx2zcx40qpnvxapp9ucct6favsvr66quuy3vnsj4wt3r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T09:41:29Z"
    mac: ENC[AES256_GCM,data:GIxML73OQG0RHLX8n72QQg7kmhZbuM2rY1LkLmabYf/eu8ziCDvChmOkxquJy3XRiS55mlSBlOxet4IrwKwzwt73uOEMM7g6dzj2v2WW/ndGMq2Rbd7q4Xjnhzh5nAGsJRzA1n18sBzZF9X26FbRC1p+y/8jmy8/FPLk041e42k=,iv:cPGUhRT9vH2as50XVjgSiPUvbcbIgtb81e5gDjl0ARs=,tag:vQ30vyyMzdPsPihK6Y9Awg==,type:str]
    version: 3.13.3
