apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:yZ+hzbABUHY=,iv:Wdylw1PvDUCFSXYUKYTdTRzY7MpmsnvWAChszJNHjtg=,tag:YHH35CBgk+NEmn5WCq5nvQ==,type:str]
    client-secret: ENC[AES256_GCM,data:6XgCxijzOGGw9/CFvjsd3gewjyMCDwe4i8iW5016zT5NRjim1Eq4VycpZ+nZEiJc56gxGvgz1w8Tbeqv3JCYRobIw1KgE/HSXo6EL8P7aV6PCFwdyuCviA==,iv:SPMAGy5nqal89JOEcsUQEwEe7sVgEEw6ztlq5A/h6Wo=,tag:4JDWntUX3SEGj/Z5Lq4kPA==,type:str]
    cookie-secret: ENC[AES256_GCM,data:Cu2L2l0huiH8DA6zkAf5y5hrpkgXsKLKrt97uhGGGI6WNBwJCZYGkdHNJS5h8DOYSfLbgj3I/MWoGCPF,iv:wY+9COqUwOmA8FWUJGbjRT9XNfjsRGyivz/cgzxHodA=,tag:jhgtvDezVc54WI5HYPGgOw==,type:str]
kind: Secret
metadata:
    name: analytics-dex-oauth
    namespace: analytics
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZGphSCtBSjkvd21EbVlk
            SzEwc0lzRXdjR0JqWEJscFZyNGRVU2U1QlVnCjArcnpWbGlJODZ3blp2cVU2aGxE
            V1F5bnBSL2E1enJDdWxCNm45L1dsbGsKLS0tIEg3Ny8yckRJVnRNT08vZDJkcnd0
            M0RaRFpJbWthWUQwZmhhcmZpR3QxQjgKPXjzY1CijMp0eERx0hxmgCYE5BphllpO
            XQCYxYybioB0kH953vL6pP1aR2N8HneF4JOfM9j7z77zxYV0sMJj5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhvf35flvr4w90jx2zcx40qpnvxapp9ucct6favsvr66quuy3vnsj4wt3r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T16:13:00Z"
    mac: ENC[AES256_GCM,data:/os5lMPk/IGdB7CJrCsrSkMYrlL8xMlKMWHkoSz49VIQachYBMydgyiJCc/DHGfaUB+WoEEqkORaDX9/UaeDQ3CUQ2pv3+4wD/fnZuBh0KqnO6izrbWjZnzgN2rtNXe3pWpnjxatX9HEST4DezhR0mhf6IrbdFOx/I6tdleEg+Q=,iv:9vwswh1SPfCQqg3JO9+qsIs4S60Go1+kCctYUPR0SeA=,tag:zQBKax/pPOA5u/wqxoW/WQ==,type:str]
    version: 3.13.3
