apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:zH2HLyVzL9Hukr3hZBYqrHtj+sq/6g0PU1bgA71lG8s6DemHGP4Go+FZT+8DukKl6/BXMIAGFtFbM++aWsDZB8sTU8fyxDEnOGSi2tAEe+XjusseQeNXQ6hthtzRjxGV0XcRFg==,iv:ooO1j7hme3yvTD6uhibcA5Qr6BKvPt34FYGZG4axRuA=,tag:7gil/u1HMfSw6swCOzVI/w==,type:str]
    client-secret: ENC[AES256_GCM,data:hJ/mHMYGcLfY1R7dt7nrS/+MdtsFuuEqmr3+l83Acz89n8FsR42xVd38y+2zIa9h,iv:RSWzI+vjTx2NjuOBfCLWhSpkNsqoh5HuFkvbeNBt6to=,tag:zrHxOKACWpDFasxSPsXahw==,type:str]
kind: Secret
metadata:
    name: dex-google-oauth
    namespace: dex
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvK04vaGlBaUw2V0dxb05i
            UE5rSWFPVEVNekQrNmpOWjRHWXZHRkRrVGdBCjJodFYyalh4QzFBVEdVMjJ1OEpY
            RTlDaGorMDZxWkxLZVZuMzJCK0UreFEKLS0tIHBzMHpEaUVaVEFHK1B0alcxUW4w
            VW5CNHpSQjBWTHVuTnd0cFJZVkZxcVUK3D/tJxNvZY4frL5C4fMYFHd1pc8xxqX3
            Y91jOetnhvLZYO688kDxE36ZBMimBtpjhZFgaRx4TcenrgBBeuCY+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhvf35flvr4w90jx2zcx40qpnvxapp9ucct6favsvr66quuy3vnsj4wt3r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T16:13:00Z"
    mac: ENC[AES256_GCM,data:Kx6UaIhTzd++5wIZE0/cq5aBpASYVFeFnZkv2vS/TJi8qd2pJ7qrXnnJSFCO2RQoThEcPh+9BeFPyJZkU6L30QfuJ9fcKO8Dbi3dElkXa1Q6AM6r6lNqltZkHqOH/EHnXJrHn0Z3V62Axepu5efLxsQCdG+0BU2A5Iqa9UQAVHg=,iv:aJtfVKhIJh0e9UhWJwFwRZLMIayU3c7JBNH+hA7x/zc=,tag:81wAwbXV3N0glCUwRwLpUA==,type:str]
    version: 3.13.3
