apiVersion: v1
data:
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:dxchOwt3kKO3+QBr6CA39AskVlunqpTl7JPi8c817gbuPnYGLHnzrTiRUzMRGNtdrdFb7w0gYGrJmfBtjnqPLOAMptYsnoL+,iv:GrMuvPZ3Cca60X36UOrryXRiqh7KU9N7LGRbIa3Zh9M=,tag:F2jKx4WCpsp4OoWVtQUmDw==,type:str]
kind: Secret
metadata:
    name: traefik-cloudflare
    namespace: kube-system
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZnF0T21Wa0dXU05kYUcv
            WmsxVlQvZnFLVkt2dnRYN1Rsczk2QmlyaVJnClNBall0S3h6V04yUXRjdXd2K0JC
            elZuSmltNUxCU1cyandZV29UZVBwTVEKLS0tIEE0ZUhubjdEdDZWbW15OEtMeXJr
            YkVmdko1TFRHK1M1OTlGek0xT2k3SmsKVviciYMibt2PidVp62lZXBJdLxw4bb47
            tTFz8WPx5hkjaADS44vUH/TCWG/n+AJUSRScqUQ9AzT9rVchYNoRCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhvf35flvr4w90jx2zcx40qpnvxapp9ucct6favsvr66quuy3vnsj4wt3r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T16:12:19Z"
    mac: ENC[AES256_GCM,data:6YTs2mCpEAhGttJfHFFTB3jHSjJ/9PcZoJrarZIxUnPsKXrNaWktOpE1gyuHLqo5/iJf/dt4krCCRyLSV1Y6S2BLldQJo6a4rkFOwv0Q+eXMpPFmfm3qhzGGAHhfrA1kiBNG5v0bXWXegUV13djwZkl0/BAExnqju4hQxc7+QgM=,iv:KCJJ2TyZe6Vgqw51Hl/I4H/HuzQHu//T2nWU4d7PY0o=,tag:5vbtV3RhmMwZDGtxjU4DLw==,type:str]
    version: 3.13.3
