apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-system-traefik-cloudflare.yaml
  - flux-system-flux-web-client.yaml
  - dex-dex-google-oauth.yaml
  - dex-dex-client-secrets.yaml
  - headlamp-headlamp-dex-oauth.yaml
  - analytics-analytics-dex-oauth.yaml
  - analytics-goatcounter-admin.yaml
