apiVersion: v1
kind: Secret
metadata:
    name: mutandae-source-auth
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jpwScQBEE4ideFFK1YD71Adbpen39MVleGSwCDgfGO97kl5j+n2oIGbuaefHhMgCzgcWrMsmTJendkWJpaYRj6blzo4zcQSYQ5RIZPHOQ1DkQndkOufg1tBV2UXHWaYi0ofeUm4tvBNmYCuaFHzP6wjgY0uQ6/szf0xJe3JNgOou0euZVHtvNd/q2i8eEVFLvCDr+MBdL5i4K9/LJXzbO7LdDADiMMayLVgmPVOun9LeUOvV+tzH3GBQTuLtaf1Xgk0Hkw/2Sc91F3tyfygMYrN/B786pqtxbGIDQsL5GOQtwU2cnWyfgEiVzzcDd5JTbi+9gmkZDXqdZjdtwn0nfu+BNcd/HFZsgRYsj6ngbfZw3UisPf+iGee2OY2oWfCv7itPlXvm7emgSZNYNGTJdqArr8Plc1036YugXSNB4+jOHk0yjZ389H/C8cSMRt10tWpRH24ewA4fx7Vw0CW6o7yfAL1QuQuIRudLFXypvhpC9N57oAX6JEQ7ebqrdZz6Px0+EvPMo3K3RaR799Cx6j5hOQM6TLaLZ3it9WM3oJCp3NA=,iv:vyTfZF1pz8Rwo0aHRuO2OVY7O5XmDSM9MbBMhN8hXcc=,tag:wNcQClisCS4FXK9Yg5cbXg==,type:str]
    identity.pub: ENC[AES256_GCM,data:XM44O1z8t5GAUarvsxptYdX5+FkwH/Og36ZqOGVObUdpEPC/wdh1U2/kOKQqMt6tIp7mIfuT0EakZb10Q2fjMu2HM9QjdJ4erzn0qG4d1ajU,iv:m6z9k0u4AML2avLgHymRec7+06Rm14tXH7ToKcC0qHo=,tag:cRSP+nB8dDv3XI1bym1iYQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:F9hISuFzIMWrWZtusadOCzVwzEYI9FmHMp502/ajMvTfqm46muYH/BP9JvQEgD27G+FX+PZtP2RHWEJ4JXLYk7Q5UGrl5T/7Md+hTMXX3UkvffgO9UXzmDTk/8uC4E6FilOh6IWdaPw2zDnf+Z6uNUnPcflT+IjlYTulvfGNCIt3HSjJ3vowVsnQfPEXNYcECEVqpOP0nfjMM6qotTo58nu+AxVFqYuXmIHg,iv:myko1Kj20/LGhoWS01HPn9Pp5SO9AP493r5jSfwCDiA=,tag:jL2EvkAtAeqEFZ7RTdJPjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TFJHRjNJYlM1NDBnV3M1
            d21WNzh6WWYyRWZYWlhXVmVvWUJrTlVGUUNFCnNZbkhwN3I1RGtNUUtXOEdKWXZN
            aERXcHZJcTlmTS9JQTlwQWljQlAySW8KLS0tIDdhRmhrVmVONis1VEhLNGU2RDMy
            d3EvNGRMalN2TFdZWE5sY1RINDNNeDQK6CnipWxWgSGNKAsZwdSjvKxuXOdzoKia
            rYrtnTWOLbJ1N0eNYwq6bpLxIRhfJljDsAoBQFN1ebPCslQCDgRhUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhvf35flvr4w90jx2zcx40qpnvxapp9ucct6favsvr66quuy3vnsj4wt3r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T14:05:19Z"
    mac: ENC[AES256_GCM,data:pv+KmhpKNLLjm/SkgWeo4mIZZBcKwZR5oJ+M8l1yH/vq3wDvLZPB2F9Q2dZlkb9jMZ1Ieet0eimm7BGo79KnBYngxKWK23xiA2LnPoOzwmdEzjuJeQy3WivdEHW6d/40+snV7Mn6XFOs+NkoNr8xiwBrCTSEEoZxVMxDRaF2VUw=,iv:DF+Tmy9GWNyI2C9yorElUZACEzNP+QRF92MTICvz240=,tag:GvUg6Z223qVb8XmMkhvQzg==,type:str]
    version: 3.13.3
