apiVersion: v1
kind: Namespace
metadata:
  name: analytics
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    belacca.com/component: analytics
---
apiVersion: v1
kind: Namespace
metadata:
  name: dex
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    belacca.com/component: identity
---
apiVersion: v1
kind: Namespace
metadata:
  name: headlamp
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    belacca.com/component: dashboard
