apiVersion: v1
kind: Namespace
metadata:
  name: backup-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    belacca.com/component: backup
---
apiVersion: v1
kind: Namespace
metadata:
  name: analytics
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    belacca.com/component: analytics
---
apiVersion: v1
kind: Namespace
metadata:
  name: dex
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    belacca.com/component: identity
---
apiVersion: v1
kind: Namespace
metadata:
  name: headlamp
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    belacca.com/component: dashboard
---
apiVersion: v1
kind: Namespace
metadata:
  name: azure-without-azure
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    belacca.com/project: azure-without-azure
    belacca.com/component: application
