apiVersion: v1
kind: Namespace
metadata:
  name: analytics
  labels:
    belacca.com/component: analytics
---
apiVersion: v1
kind: Namespace
metadata:
  name: dex
  labels:
    belacca.com/component: identity
---
apiVersion: v1
kind: Namespace
metadata:
  name: headlamp
  labels:
    belacca.com/component: dashboard
