apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: oauth2-proxy
  namespace: analytics
  labels:
    belacca.com/stage: native-production
    belacca.com/project: analytics
    belacca.com/component: analytics-auth
spec:
  interval: 1h
  url: https://oauth2-proxy.github.io/manifests
