apiVersion: v1
data:
    email: ENC[AES256_GCM,data:t/yoWX58wf3JiohNhNylLtTQ95Z2o4vy,iv:6cFdopLNf2gA2NrhqcOq0PhQVPRIYuCUK7zdzjmwQIY=,tag:cLvuu02b2ykjXGcX8xQCEg==,type:str]
    password: ENC[AES256_GCM,data:8ImHVW3rxVALmBVwcq5xlWyICvnJ+/Qm7opV0H0ILUD5dPmc9Q0CNcPSDgpaJw8BXL1iV0dJnyg=,iv:3s6u7Ryt7Ml+Ahzy2eZ3LTa0dSoGghbcTIQdzB53seg=,tag:f5TcRCNS0DBSo813yRiKmA==,type:str]
kind: Secret
metadata:
    name: goatcounter-admin
    namespace: analytics
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYk94SDRJdlFORWxKYVFD
            bFd2amJ6aEo2YjZiYXJMRW54eHZrbTJwankwCnk0YzRLaC9qZ2V1cFpxVDlNRTdF
            OEk0TWpzWkhjejdsaVZHN2RVcVRRZUEKLS0tIEJ4NFZmZW92dUpiSllqTTBQS3Jz
            KzBXc1k4K1htQnd4R1JUWFo4K1ZEVDQKb4Msa631JcARtqYJX+S1V/G10trzTEhP
            F/lF7yJnmshoR/ou56RdsoqJ23VCJURfAVanCXAZz6WnMIbjHajRYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhvf35flvr4w90jx2zcx40qpnvxapp9ucct6favsvr66quuy3vnsj4wt3r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T16:13:00Z"
    mac: ENC[AES256_GCM,data:7qhv31OVyJwde01+tvWO2kJIFRtn6+poP0x5GiIz/c8n7j76RE/xM6LvL+LjVqOFEPJ11ORyLKIjmzzX2EJUkRAfA/DS4Na4F8z3KiQBZguOzcPx2iawoZ6c72NTkMWOE4JYJAdJr0zcrXVB/7VgOkCExBJciPo6v6EjARqjS7Q=,iv:JUOfglQEdJ4eiW9SvvrvBenEDxEvcJR2BzXS/Mc+RJ0=,tag:1tga86Qu43x65aiNsyskHQ==,type:str]
    version: 3.13.3
