apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-web-chart
  namespace: flux-system
  labels:
    belacca.com/stage: native-production
    belacca.com/project: platform
    belacca.com/component: flux-web
spec:
  interval: 1h
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    semver: "0.58.1"
