apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:I9UWD1aOlZoayp7Z,iv:TFJH+j0n6OUs5MSgjMX0V3L9iX5KBYOzEFrdCzYa/c8=,tag:h3TdpEmXiwjB6wp+mxmudg==,type:str]
    client-secret: ENC[AES256_GCM,data:3wFnZgFyxyeoo0FlsY1UOnOR6ECMM5TtdFUNeS03lNVpL7aok529/3fCiEqloFYQ4GPLADGsSxbsdlIb7Wj/m1hTWsgbgZ8q+VQO2F4AzY2mI4MgzG3rTA==,iv:rx7kXUkda2yslJtf6kl2wRzeXdyW/LOG4wkQznQlxps=,tag:MF6ki/0WjCIlEf/AXjHJRw==,type:str]
kind: Secret
metadata:
    name: flux-web-client
    namespace: flux-system
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYjIzZEVCYmFqdzJNZ2R3
            MlowN1M1V2hua2FIM0xHaEdIcXozMnArbVM4CngzeEhXWnh5VVZQKzdSSWNWQWN5
            K0ZjZlRmc0RjVUJjZFplK2tRVklKQTQKLS0tIG81bEtxTGdxbGdPR3pHZzJNNWwv
            cFdUTzRrZ0NvSUVrYlp6SDB3RjFuUVEKlR4bKSTJ12q+iZSi8TPiu5KmydnkopaA
            NF21a7ItUt/zjY2YoosxM2wOoNd/RPlKnnoZkyP2sJsnDNJh7zo4UQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhvf35flvr4w90jx2zcx40qpnvxapp9ucct6favsvr66quuy3vnsj4wt3r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T16:13:00Z"
    mac: ENC[AES256_GCM,data:R9KotRP84PZxzwFPq8MuqM8lJV7myMdXeQlm61CVotKeWBzuhsQZxB+sf9Ew0ryuKbDBNRg+LYGoFUMy1Qf7JgOArfcPuG8sMKPD361f5NdcKXWTIQeIzZOYGKsWfijlb6qmL78ZSaJqAg0BIJEN71akSPdWhvYB8Qkp166sVrQ=,iv:D6a8N7UECHSY+pcZ8eWjCvHKdR38RrfUC03kuoTUVKo=,tag:UvO5dfnk2rf9EWa7iJzi3w==,type:str]
    version: 3.13.3
