apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headlamp
  namespace: headlamp
  labels:
    belacca.com/stage: native-production
    belacca.com/project: platform
    belacca.com/component: dashboard
spec:
  interval: 1h
  url: https://kubernetes-sigs.github.io/headlamp/
