apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: oauth2-proxy
  namespace: headlamp
  labels:
    belacca.com/stage: native-staging
    belacca.com/project: platform
    belacca.com/component: headlamp-auth
spec:
  interval: 1h
  url: https://oauth2-proxy.github.io/manifests
