apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:mLtAeT/95NvnrJ2T,iv:6Bd3c7AtNsMty2dwqttk8If72hVKQYmgCxkOv8GJQ+A=,tag:Hi0DG7xKi80wZ20l6IN2KA==,type:str]
    client-secret: ENC[AES256_GCM,data:TbU9Ta+LG5J7ayu0Kr5Tx1RdDznuqOv70oakSQSA18w1afCYXTdXmi4Fx+zD8t24Q4ZZnEvLEeNtqD0uSusbm4FlPsJrQFt1mZL8iPK87yRI01xk3K0jFw==,iv:eAlZDPTWVdFCVVUonifslGQWThoPtAICUdDmeZ/MaMw=,tag:FA/6c9a7MJMtPf3FHs21ug==,type:str]
    cookie-secret: ENC[AES256_GCM,data:5N1Zehdxr6IsLuRwVFXlW9rwk5VkV2kbwWQdumGdblkvZcEBSoZlNnh+Sp51wNfl34r3yNtbe9zCxAlp,iv:JKumJgPICN2dxY4561xfwZdB1mRob5dxHT5MFHGyQ9s=,tag:u0xQs7/iXtoB7oFU5ZBZNw==,type:str]
kind: Secret
metadata:
    name: headlamp-dex-oauth
    namespace: headlamp
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UG5taGhxb3RmMWFWUmti
            bWZRVWNMZHNFc1dYb0VjTWlzVjQ5SFI0NWlFCm00UVhNQ1Q0NC9xcUJhUHNaTDds
            NGRySjU4RGhDWjdxbGU2cjRaVlhybTAKLS0tIDhzQ0NKbkNVMTZmaXRlSGFtZjBL
            bi9CUWFpU3hmY21aNDhPUUE2ZzFodDAKJ8cuoAh6gVHcIFthXMuOMqm3GyV1zcp8
            dUa3HC4yikiysOD6Z+L+HA+5OtDBoMbtLAcdhZb+RTRZt1Y+7/CKmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhvf35flvr4w90jx2zcx40qpnvxapp9ucct6favsvr66quuy3vnsj4wt3r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T16:13:00Z"
    mac: ENC[AES256_GCM,data:G+SpYWGdn+XNlVPPdk9YYsTzYmLJWGqZleJqn385nKcRG09+ucUOYr3kuXUXgjbiWhr7APq3KGB8locVTvI24/FtTaPrl5/Gzn27BR1k0CXUg2JQOFFQLtJzN6I60AsjB74m+zumICexOsg9U//ugPdtLOOkkanL0y/cUIYvLNM=,iv:z7W2abLYNf+Mt1zllSR2Q552SOzA8PMoxAgaCJ/WErE=,tag:lL8C2eqc+xS0IsLSkUc0vA==,type:str]
    version: 3.13.3
